### ISSUE TITLE
sidemission: crashed sdvs

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#27]
**task: crashed sdvs**
* underwater combat
* intel has to be taken to base

**Sucess**
* reveals location of mission targets

**Failure**
* no intel

> @iJesuz: i'm currently working on:

**Comment by iJesuz** [comment]
on failure maybe something like 'The enemy has taken the intel from our SDV and is now able to call artillery fire on our positions near the AO.'
