### ISSUE TITLE
sidemission handling

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#30]
- [ ] integrate the sidemissionhandling into mission creating
- [x] more then 1 sidemission during 1 main mission

**Comment by iJesuz** [comment]
maybe we should change the intel types if we want to spawn more than one side mission to make them less over powered: 
* reduce intel number massily
* new intel types
  * hacking satellite telefons will display all enemy hqs
  * show main patrol routes
  * give grids colors depending on enemy number
  * maybe a mystery to solve
* or something completely different

**Comment by Dorbedo** [comment]
d0a5663f941789e842cd554dc7bb0a55a577a81b

**Comment by Dorbedo** [comment]
3b0d7d93beca2e679c275e39f42de3ef970c450a

and closed
