### ISSUE TITLE
Sidemission: Bugs

### ISSUE THREAD

**Issue by iJesuz** [Dorbedo/Operation_Kerberos#48]
general:
- [ ] reward function is called but doesn't work (targets part)
- [x] change DORB_MISSION_FNC (wrong initialized at some places)
- [ ] seems like they don't cancel sometimes

deserter:
- [ ] 

aircraft:
- [x] randomization of wrack position
- [x] better placement

supplies:
- [x] rewrite description (still AAF in description, what shall be delivered?)

sdv:
- [ ] main mission canceled
- [ ] ground and surface mines are deployed at right position but change position after about 0.1 seconds
- [x] may change spawn radius to make it more difficult
- [ ] enemy units still not spawned

**Comment by Dorbedo** [comment]
still no sdv's spawned

**Comment by kitoma** [comment]
Heute auch, Minen waren da, aber (in 100m Umkreis) kein SDV am Meeresgrund.
