### ISSUE TITLE
IGI-Load improvement

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#59]
- [ ] add RHS-Vehicles
- [ ] add additional Containers (freight pallet, .... )

**Comment by Dorbedo** [comment]
6b137b9b7fa88cb297e05d70fac121997cc84bc4

**Comment by iJesuz** [comment]
In respect to the upcomming weekend madness we should add the following USAF Vehicles:
* [ ] C-17 Globemaster
* [ ] C-130
* [ ] C-5 Galaxy
* [ ] CV-22 Osprey

**Comment by Dorbedo** [comment]
IgiLoad will be removed with #60
