### ISSUE TITLE
Arma 1.50 new Commands

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#66]
- [x] Check if onlyPilots works
- [x] splitstring (remove BIS & CBA)
- [x] joinstring
- [x] targetKnowledge
- [x] remoteExec
- [x] remoteExecCall
- [x] CfgRemoteExec
- [x] "SeatSwitched" Eventhandler - no XEH atm
- [x] OnPlayerConnect
- [x] OnPlayerDisconnect
- [x] getAllHitPointsDamage / setHitIndex / getHitIndex
- [x] lineIntersectsSurfaces
- [x] AGLToASL / ASLToAGL

**Comment by iJesuz** [comment]
- [ ] getModelInfo for fnc_log_getCargoCfg.sqf
- [ ] new ability of #include to use '..' in path

**Comment by Dorbedo** [comment]
New Structure ( '..\ability')
b8db3941357a2fdf7a435e610c095b4b6d8653a6 435f9b92f6186524e764c6f84df3ccf4decabac7 a111ff04ab3482176fc2185bb69402d7a0361133  1568c6ac4c4f62242517f24b01d5a0a1abb11642 87716a6d05b70e5e81c7d3e4de0382d7ae5c0a3b 54c648df4ac83d215f644f877307a18ff58aa22a
