### ISSUE TITLE
Medic Truck defect?

### ISSUE THREAD

**Issue by kitoma** [Dorbedo/Operation_Kerberos#71]
Something appears to be wrong with the medic truck in the base (next to the logistics point). after unlocking and entering it, I could only switch between driver/passenger, but neither "get out" nor "eject" worked = I was stuck there. After respawning, arma was still rather.. broken, so I actually had to relog.

**Comment by Dorbedo** [comment]
You should not experiment with the ACE-Keys....
This Truck is just a MHQ and not meant to be moved.
I'll lock him completely.

**Comment by kitoma** [comment]
Na es ist halt ein Spiel, da probieren die Leute rum ;)
Ich wollte den Truck auch gar nicht wegfahren, ehrlich gesagt hab ich nur gesucht, ob da evtl. ein NPC-Sani versteckt waere, der mir mal einen Infusion haette laufen lassen koennen. Die Funktionsweise der anderen Sani-Location hab ich irgendwie immer noch nicht verstanden -g-

**Comment by Dorbedo** [comment]
Die hat keine im Basic-Medical.
Wenn Advanced an ist, ist die ein Medic-HQ.
