### ISSUE TITLE
only pilots

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#73]
- [x] integrate the seat switched EH into onlyPilots
- [x] some hueys can be entered by non whitelisted players

**Comment by iJesuz** [comment]
Eventhandler is called if it is assigned manualley. It seems like Extended_SeatSwitched_Eventhandlers doesn't work correctly at the moment.

**Comment by iJesuz** [comment]
Script works correctly after Dorbedos typo fix.
